In [1]:
import numpy as np 

In [9]:
vector = np.array([1,2,3,4,5,6])
matris = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])

In [3]:
print(vector)

[1 2 3 4 5 6]


In [11]:
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [23]:
vector.size  #kaç elemanlı olduğunu veriyor

6

In [22]:
matris.size  #kaç elemanlı olduğunu veriyor

12

In [14]:
vector.shape  #satır ve sütunları verir vectörümüz 

(6,)

In [13]:
matris.shape  #satır ve sütunları verir 

(4, 3)

In [19]:
vector.ndim  #uzayda kapladığı boyut

1

In [18]:
matris.ndim  #uzayda kapladığı boyut

2

In [20]:
vector.dtype

dtype('int32')

In [21]:
matris.dtype

dtype('int32')